# Generated by Django 4.0.2 on 2022-04-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_avatar'),
        ('likes', '0005_alter_likes_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Like', max_length=100)),
                ('summary', models.CharField(blank=True, max_length=250)),
                ('context', models.URLField(default='https://www.w3.org/ns/activitystreams')),
                ('object', models.URLField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
