# Generated by Django 4.0.2 on 2022-04-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_author_comment_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=100),
        ),
    ]
