# Generated by Django 4.0.2 on 2022-03-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_comments'),
        ('posts', '0006_alter_post_visibility'),
    ]

    operations = [
    ]
