# Generated by Django 4.0.2 on 2022-04-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_inboxitem_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
